name: Sync libdebug gh-pages into main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout libdebug gh-pages
        uses: actions/checkout@v4
        with:
          repository: libdebug/libdebug
          ref: gh-pages
          path: libdebug-pages
          fetch-depth: 1

      - name: Sync files from gh-pages
        run: |
          # copy all files over, but leave existing files intact and skip any .git dirs
          rsync -av libdebug-pages/ . \
            --exclude '.github/**' \
            --exclude '.git' \
            --exclude '.git/**'

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "✅ Nothing to commit."
          else
            git add --all
            git commit -m "chore: sync content from libdebug/libdebug@gh-pages"
            git push origin main
          fi
